In [1]:
# Imports

import math
import random
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
from collections import namedtuple
from itertools import count
# from PIL import Image

import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F
import torchvision.transforms as T

In [2]:
import cv2

In [4]:
hero = cv2.imread("./images/mainMonster.jpg")
print(hero.shape)
hero = cv2.resize(hero, (64,64))
cv2.imshow("window1",hero)
# cv2.waitKey()
# cv2.destroyAllWindows()

(1080, 1080, 3)


In [3]:
otherPlayer = cv2.imread("./images/otherMonster.jpg")
print(otherPlayer.shape)
otherPlayer = cv2.resize(otherPlayer, (64,64))
cv2.imshow("window2",otherPlayer)
# cv2.waitKey()
# cv2.destroyAllWindows()

(600, 800, 3)


In [5]:
smallFruit = cv2.imread("./images/smallFruit.png")
print(smallFruit.shape)
smallFruit = cv2.resize(smallFruit, (64,64))
cv2.imshow("window3",smallFruit)
# cv2.waitKey()
# cv2.destroyAllWindows()

(588, 880, 3)


In [6]:
bigFruit = cv2.imread("./images/bigFruit.jpg")
print(bigFruit.shape)
bigFruit = cv2.resize(bigFruit, (64,64))
cv2.imshow("window4",bigFruit)
cv2.waitKey()
cv2.destroyAllWindows()

(719, 800, 3)


In [7]:
print(hero)

[[[242 216 150]
  [242 216 150]
  [242 216 150]
  ...
  [242 216 150]
  [242 216 150]
  [242 216 150]]

 [[242 216 150]
  [242 216 150]
  [242 216 150]
  ...
  [242 216 150]
  [242 216 150]
  [242 216 150]]

 [[242 216 150]
  [242 216 150]
  [242 216 150]
  ...
  [242 216 150]
  [242 216 150]
  [242 216 150]]

 ...

 [[242 216 150]
  [242 216 150]
  [242 216 150]
  ...
  [242 216 150]
  [242 216 150]
  [242 216 150]]

 [[242 216 150]
  [242 216 150]
  [242 216 150]
  ...
  [242 216 150]
  [242 216 150]
  [242 216 150]]

 [[242 216 150]
  [242 216 150]
  [242 216 150]
  ...
  [242 216 150]
  [242 216 150]
  [242 216 150]]]


In [11]:
print(hero.shape, otherPlayer.shape, smallFruit.shape, bigFruit.shape)

(64, 64, 3) (64, 64, 3) (64, 64, 3) (64, 64, 3)


In [12]:
# Render Help Functions

def overWrite(startI, startJ, originalImage, smallImage):
    for i in range(smallImage.shape[0]):
        for j in range(smallImage.shape[1]):
            originalImage[startI + i][startJ + j] = smallImage[i][j]
    return originalImage

# def displayBoard(board, direction, ownI, ownJ):
def displayBoard(board, ownI, ownJ):
    # board is the board position matrix of size 6x9 such that player is at index [5][4] (bottom center)
    image = np.zeros((64*9, 64*9, 3), dtype = np.uint8)
    board = np.asarray(board)
    print(board)
    for i in range(board.shape[0]):
        for j in range(board.shape[1]):
            if board[i][j] == 1:
                overWrite(64*i,64*j,image,otherPlayer)
            elif board[i][j] == 2:
                overWrite(64*i,64*j,image,smallFruit)
            elif board[i][j] == 3:
                overWrite(64*i,64*j,image,bigFruit)
    overWrite(64*ownI,64*ownJ,image,hero)
    return image
    

In [13]:
# Static movement and rendering:

In [ ]:
mainServer = 5001

# Dummy user:

req = {
'agentId': 1007,
'initial_i': 19,
'initial_j': 28
}

res = requests.post("http://localhost:{}/addAgent".format(mainServer), json = req)
# print(res)

# Real Agent:

req = {
'agentId': 123,
'initial_i': 20,
'initial_j': 23
}

res = requests.post("http://localhost:{}/addAgent".format(mainServer), json = req)
# print(res)

req = {
	'agentId': 123
}
resField = requests.post("http://localhost:{}/checkField".format(mainServer), json = req)
# print(resField.json().content)

# cv2.imshow("window", displayBoard(resField, 5, 5))
# cv2.waitKey()

# for i in json.loads(resField.json().get("field")):
# 	for j in i:
# 		print(j, end = " ")
# 	print()

ch = int(input("\n\nEnter direction choice:\nPS: 6 to exit\n\n"))

req = {
	'agentId': 123
}
resField = requests.post("http://localhost:{}/checkField".format(mainServer), json = req)
field = json.loads(resField.json().get("field"))

print(type(field))
print(field)
print(type(field[0]))

cv2.imshow("window", displayBoard(field, 5, 5))
cv2.waitKey(20)
# for i in field:
# 	for j in i:
# 		print(j, end = " ")
# 	print()

while True:
	ch = intelligentPlayer()

	req = {
	'agentId': 123,
	'action': str(ch)
	}
	# print(req)
	res = requests.post("http://localhost:{}/moveAgent".format(mainServer), json = req)
	# print(res)

	req = {
	'agentId': 123
	}
	resField = requests.post("http://localhost:{}/checkField".format(mainServer), json = req)

	field = json.loads(resField.json().get("field"))
	img = displayBoard(field, 4, 4)
	print("Here before displaying:\n\n")
	cv2.imshow("window", img)
	cv2.waitKey(20)
	print("Here!")
# 	for i in field:
# 		for j in i:
# 			print(j, end = " ")
# 		print()

cv2.destroyAllWindows()



In [ ]:
# RL help functions
def getField():
    field = json.loads(resField.json().get("field"))
    return np.asarray(field)

def moveAgent(moveValue, agentID):
    
    req = {
        "agentID": agentID,
        "action": str(moveValue)
    }
    
    res = requests.post("http://localhost:{}/moveAgent".format(mainServer), json = req)
    
    return res
    


In [ ]:
Transition = namedtuple('Transition',
                        ('state', 'action', 'next_state', 'reward'))


class ReplayMemory(object):

    def __init__(self, capacity):
        self.capacity = capacity
        self.memory = []
        self.position = 0

    def push(self, *args):
        """Saves a transition."""
        if len(self.memory) < self.capacity:
            self.memory.append(None)
        self.memory[self.position] = Transition(*args)
        self.position = (self.position + 1) % self.capacity

    def sample(self, batch_size):
        return random.sample(self.memory, batch_size)

    def __len__(self):
        return len(self.memory)

In [70]:
class DQN2(nn.Module):

    def __init__(self, h, w, outputs):
        super(DQN2, self).__init__()
        self.conv1 = nn.Conv2d(3, 16, kernel_size=5, stride=2)
        self.bn1 = nn.BatchNorm2d(16)
        self.conv2 = nn.Conv2d(16, 32, kernel_size=5, stride=2)
        self.bn2 = nn.BatchNorm2d(32)
        self.conv3 = nn.Conv2d(32, 32, kernel_size=5, stride=2)
        self.bn3 = nn.BatchNorm2d(32)

        # Number of Linear input connections depends on output of conv2d layers
        # and therefore the input image size, so compute it.
        def conv2d_size_out(size, kernel_size = 5, stride = 2):
            return (size - (kernel_size - 1) - 1) // stride  + 1
        convw = conv2d_size_out(conv2d_size_out(conv2d_size_out(w)))
        convh = conv2d_size_out(conv2d_size_out(conv2d_size_out(h)))
        linear_input_size = convw * convh * 32
        print(linear_input_size, convw, convh)
        self.head = nn.Linear(linear_input_size, outputs)

    # Called with either one element to determine next action, or a batch
    # during optimization. Returns tensor([[left0exp,right0exp]...]).
    def forward(self, x):
        x = F.relu(self.bn1(self.conv1(x)))
        x = F.relu(self.bn2(self.conv2(x)))
        x = F.relu(self.bn3(self.conv3(x)))
        return self.head(x.view(x.size(0), -1))

In [73]:
trial2 = DQN2(90,90,5)

2048 8 8


In [64]:
initialState = np.zeros((10,3,90,90))
# initialState
initialState = torch.tensor(initialState, dtype = torch.float32)
initialState[0]

tensor([[[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]],

        [[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]],

        [[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]]])

In [67]:
res = trial2(initialState)
print(res)
print(res.max())
print("\n\n\n")
print(res.max(1))
print(res.max(1)[0])

tensor([[-0.0152,  0.0155, -0.0158, -0.0060, -0.0127],
        [-0.0152,  0.0155, -0.0158, -0.0060, -0.0127],
        [-0.0152,  0.0155, -0.0158, -0.0060, -0.0127],
        [-0.0152,  0.0155, -0.0158, -0.0060, -0.0127],
        [-0.0152,  0.0155, -0.0158, -0.0060, -0.0127],
        [-0.0152,  0.0155, -0.0158, -0.0060, -0.0127],
        [-0.0152,  0.0155, -0.0158, -0.0060, -0.0127],
        [-0.0152,  0.0155, -0.0158, -0.0060, -0.0127],
        [-0.0152,  0.0155, -0.0158, -0.0060, -0.0127],
        [-0.0152,  0.0155, -0.0158, -0.0060, -0.0127]],
       grad_fn=<AddmmBackward>)
tensor(0.0155, grad_fn=<MaxBackward1>)




torch.return_types.max(
values=tensor([0.0155, 0.0155, 0.0155, 0.0155, 0.0155, 0.0155, 0.0155, 0.0155, 0.0155,
        0.0155], grad_fn=<MaxBackward0>),
indices=tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1]))
tensor([0.0155, 0.0155, 0.0155, 0.0155, 0.0155, 0.0155, 0.0155, 0.0155, 0.0155,
        0.0155], grad_fn=<MaxBackward0>)


In [66]:
res.shape

torch.Size([10, 5])

In [85]:
# DQN network
class DQN(nn.Module):

    def __init__(self, h, w, outputs):
        super(DQN, self).__init__()
#         self.conv1 = nn.Conv2d(3,1,3)
#         self.flattener = nn.Flatten(h*w)
        self.lin1 = nn.Linear(h*w, 64)
        self.lin2 = nn.Linear(64, outputs)

    def forward(self, x):
#         x = self.flattener(x)
        print(x.shape)
        x = x.reshape(x.size(0),-1)
        print(x.shape)
        x = x.squeeze()
        print(x.shape)
        x = F.relu(self.lin1(x))
        print(x.shape)
        x = F.relu(self.lin2(x))
        print(x.shape)
        return x

In [86]:
trial = DQN(9,9,5)

In [87]:
initialState = np.zeros((10,1,9,9))
# initialState
initialState = torch.tensor(initialState, dtype = torch.float32)
initialState[0]

tensor([[[0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0.]]])

In [89]:
res = trial(initialState)
print(res)
print(res.max())
print(res.max(1))
print("\n\n\n")
print(res.max(1)[1])
print("\n\n\n")
print(res.max(1)[1].view(1,1))

torch.Size([10, 1, 9, 9])
torch.Size([10, 81])
torch.Size([10, 81])
torch.Size([10, 64])
torch.Size([10, 5])
tensor([[0.0000, 0.0858, 0.0442, 0.0020, 0.0000],
        [0.0000, 0.0858, 0.0442, 0.0020, 0.0000],
        [0.0000, 0.0858, 0.0442, 0.0020, 0.0000],
        [0.0000, 0.0858, 0.0442, 0.0020, 0.0000],
        [0.0000, 0.0858, 0.0442, 0.0020, 0.0000],
        [0.0000, 0.0858, 0.0442, 0.0020, 0.0000],
        [0.0000, 0.0858, 0.0442, 0.0020, 0.0000],
        [0.0000, 0.0858, 0.0442, 0.0020, 0.0000],
        [0.0000, 0.0858, 0.0442, 0.0020, 0.0000],
        [0.0000, 0.0858, 0.0442, 0.0020, 0.0000]], grad_fn=<ReluBackward0>)
tensor(0.0858, grad_fn=<MaxBackward1>)
torch.return_types.max(
values=tensor([0.0858, 0.0858, 0.0858, 0.0858, 0.0858, 0.0858, 0.0858, 0.0858, 0.0858,
        0.0858], grad_fn=<MaxBackward0>),
indices=tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1]))




tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])






RuntimeError: shape '[1, 1]' is invalid for input of size 10

In [84]:
# resize = T.Compose([T.ToPILImage(),
#                     T.Resize(40, interpolation=Image.CUBIC),
#                     T.ToTensor()])


# def get_cart_location(screen_width):
#     world_width = env.x_threshold * 2
#     scale = screen_width / world_width
#     return int(env.state[0] * scale + screen_width / 2.0)  # MIDDLE OF CART

# def get_screen():
#     # Returned screen requested by gym is 400x600x3, but is sometimes larger
#     # such as 800x1200x3. Transpose it into torch order (CHW).
#     screen = env.render(mode='rgb_array').transpose((2, 0, 1))
#     # Cart is in the lower half, so strip off the top and bottom of the screen
#     _, screen_height, screen_width = screen.shape
#     screen = screen[:, int(screen_height*0.4):int(screen_height * 0.8)]
#     view_width = int(screen_width * 0.6)
#     cart_location = get_cart_location(screen_width)
#     if cart_location < view_width // 2:
#         slice_range = slice(view_width)
#     elif cart_location > (screen_width - view_width // 2):
#         slice_range = slice(-view_width, None)
#     else:
#         slice_range = slice(cart_location - view_width // 2,
#                             cart_location + view_width // 2)
#     # Strip off the edges, so that we have a square image centered on a cart
#     screen = screen[:, :, slice_range]
#     # Convert to float, rescale, convert to torch tensor
#     # (this doesn't require a copy)
#     screen = np.ascontiguousarray(screen, dtype=np.float32) / 255
#     screen = torch.from_numpy(screen)
#     # Resize, and add a batch dimension (BCHW)
#     return resize(screen).unsqueeze(0).to(device)


# env.reset()
# plt.figure()
# plt.imshow(get_screen().cpu().squeeze(0).permute(1, 2, 0).numpy(),
#            interpolation='none')
# plt.title('Example extracted screen')
# plt.show()

In [ ]:
BATCH_SIZE = 128
GAMMA = 0.999
EPS_START = 0.9
EPS_END = 0.05
EPS_DECAY = 200
TARGET_UPDATE = 10

agentID = 123

# Get screen size so that we can initialize layers correctly based on shape
# returned from AI gym. Typical dimensions at this point are close to 3x40x90
# which is the result of a clamped and down-scaled render buffer in get_screen()
init_screen = get_field()
screen_height, screen_width = 9,9

# Get number of actions from gym action space
n_actions = 5

policy_net = DQN(screen_height, screen_width, n_actions).to(device)
target_net = DQN(screen_height, screen_width, n_actions).to(device)
target_net.load_state_dict(policy_net.state_dict())
target_net.eval()

optimizer = optim.RMSprop(policy_net.parameters())
memory = ReplayMemory(10000)


steps_done = 0


def select_action(state):
    global steps_done
    sample = random.random()
    eps_threshold = EPS_END + (EPS_START - EPS_END) * \
        math.exp(-1. * steps_done / EPS_DECAY)
    steps_done += 1
    if sample > eps_threshold:
        with torch.no_grad():
            # t.max(1) will return largest column value of each row.
            # second column on max result is index of where max element was
            # found, so we pick action with the larger expected reward.
            return policy_net(state).max(1)[1].view(1, 1)
    else:
        return torch.tensor([[random.randrange(n_actions)]], device=device, dtype=torch.long)


episode_durations = []


def plot_durations():
    plt.figure(2)
    plt.clf()
    durations_t = torch.tensor(episode_durations, dtype=torch.float)
    plt.title('Training...')
    plt.xlabel('Episode')
    plt.ylabel('Duration')
    plt.plot(durations_t.numpy())
    # Take 100 episode averages and plot them too
    if len(durations_t) >= 100:
        means = durations_t.unfold(0, 100, 1).mean(1).view(-1)
        means = torch.cat((torch.zeros(99), means))
        plt.plot(means.numpy())

    plt.pause(0.001)  # pause a bit so that plots are updated
    if is_ipython:
        display.clear_output(wait=True)
        display.display(plt.gcf())

In [ ]:
def optimize_model():
    if len(memory) < BATCH_SIZE:
        return
    transitions = memory.sample(BATCH_SIZE)
    # Transpose the batch (see https://stackoverflow.com/a/19343/3343043 for
    # detailed explanation). This converts batch-array of Transitions
    # to Transition of batch-arrays.
    batch = Transition(*zip(*transitions))

    # Compute a mask of non-final states and concatenate the batch elements
    # (a final state would've been the one after which simulation ended)
    non_final_mask = torch.tensor(tuple(map(lambda s: s is not None,
                                          batch.next_state)), device=device, dtype=torch.bool)
    non_final_next_states = torch.cat([s for s in batch.next_state
                                                if s is not None])
    state_batch = torch.cat(batch.state)
    action_batch = torch.cat(batch.action)
    reward_batch = torch.cat(batch.reward)

    # Compute Q(s_t, a) - the model computes Q(s_t), then we select the
    # columns of actions taken. These are the actions which would've been taken
    # for each batch state according to policy_net
    state_action_values = policy_net(state_batch).gather(1, action_batch)

    # Compute V(s_{t+1}) for all next states.
    # Expected values of actions for non_final_next_states are computed based
    # on the "older" target_net; selecting their best reward with max(1)[0].
    # This is merged based on the mask, such that we'll have either the expected
    # state value or 0 in case the state was final.
    next_state_values = torch.zeros(BATCH_SIZE, device=device)
    next_state_values[non_final_mask] = target_net(non_final_next_states).max(1)[0].detach()
    # Compute the expected Q values
    expected_state_action_values = (next_state_values * GAMMA) + reward_batch

    # Compute Huber loss
    loss = F.smooth_l1_loss(state_action_values, expected_state_action_values.unsqueeze(1))

    # Optimize the model
    optimizer.zero_grad()
    loss.backward()
    for param in policy_net.parameters():
        param.grad.data.clamp_(-1, 1)
    optimizer.step()

In [ ]:
num_episodes = 50
for i_episode in range(num_episodes):
    # Initialize the environment and state
    initializeAgent()
#     last_screen = getField()
#     current_screen = getField()
#     state = current_screen - last_screen
    state = getField()
    for t in count():
        # Select and perform an action
        action = select_action(state)
        
        _, reward, done, _ = moveAgent(action.item(), agentID)
        reward = torch.tensor([reward], device=device)

        # Observe new state
#         last_screen = current_screen
#         current_screen = get_screen()
        if not done:
            next_state = getField()
        else:
            next_state = None

        # Store the transition in memory
        memory.push(state, action, next_state, reward)

        # Move to the next state
        state = getField()

        # Perform one step of the optimization (on the target network)
        optimize_model()
        if done:
            episode_durations.append(t + 1)
            plot_durations()
            break
    # Update the target network, copying all weights and biases in DQN
    if i_episode % TARGET_UPDATE == 0:
        target_net.load_state_dict(policy_net.state_dict())

print('Complete')
# env.render()
# env.close()
# plt.ioff()
# plt.show()